/**
 * render-compat.mjs — generates each facet's "Upstream compatibility" README
 * section from the two places the facts already live, so the human-facing
 * table can never drift from the machine-enforced contract:
 *
 *   1. `packages/<facet>/package.json#peerDependencies` — the ENFORCED range
 *      (npm warns consumers outside it). Policy: the upper bound moves only
 *      after the verification ritual (drift gate + fixture suite ± live
 *      capture) passes against the new upstream version.
 *   2. `packages/<facet>/sdk-surface.json#verified` — the APPEND-ONLY
 *      evidence log: one entry per upstream version the ritual ran green
 *      against ({ sdkVersion, date, silverprotocol?, evidence }). The drift
 *      gate (`check-fixture-drift.mjs`) asserts the newest entry matches the
 *      installed e2e pin AND calls {@link checkCompatStaleness} so a stale
 *      rendered table fails the same gate — the log and the tables stay
 *      honest by the same mechanism.
 *
 * The rendered block replaces whatever sits between the README markers
 *   <!-- compat:begin -->  …  <!-- compat:end -->
 * Both markers must exist EXACTLY ONCE — a quoted marker anywhere else in
 * the README (e.g. inside a code fence documenting this mechanism) is a
 * hard error, never a silent mis-splice (review finding: a first-indexOf
 * splice destroyed content between a quoted marker and the real section).
 *
 * Usage:
 *   node scripts/render-compat.mjs           # rewrite stale READMEs
 *   node scripts/render-compat.mjs --check   # CI mode: exit 1 if any README
 *                                            # is stale, write nothing
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const typescriptRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const FACETS = ["claude-agent-sdk", "openai-agents", "google-adk"];
const BEGIN = "<!-- compat:begin -->";
const END = "<!-- compat:end -->";

/** Escape a value for a Markdown table cell: `|` would split the row. A
 *  missing value renders empty, never the literal string "undefined". */
function cell(v) {
  return String(v ?? "").replaceAll("|", "\\|");
}

/** The facet's upstream peer: the sole non-@silverprotocol peerDependency. */
function upstreamPeer(pkg) {
  const peers = Object.entries(pkg.peerDependencies ?? {}).filter(
    ([name]) => !name.startsWith("@silverprotocol/"),
  );
  if (peers.length !== 1) {
    throw new Error(
      `${pkg.name}: expected exactly one non-@silverprotocol peerDependency, found ${peers.length}`,
    );
  }
  return { name: peers[0][0], range: peers[0][1] };
}

function renderBlock(pkg, verified) {
  const peer = upstreamPeer(pkg);
  const rows = [...verified]
    .reverse() // newest first
    .map((v) => `| \`${cell(v.sdkVersion)}\` | ${cell(v.date)} | ${cell(v.silverprotocol)} | ${cell(v.evidence)} |`);
  return [
    BEGIN,
    "<!-- generated by scripts/render-compat.mjs — do NOT edit by hand.",
    "     Facts live in package.json#peerDependencies + sdk-surface.json#verified;",
    "     edit those, then re-run `node scripts/render-compat.mjs`. -->",
    "## Upstream compatibility",
    "",
    `Supported peer range: \`${peer.name}\` \`${peer.range}\` (npm-enforced, optional — this package never imports the SDK).`,
    "",
    "Wire shapes outside the verified set never crash the normalizer, and the",
    "fixture-drift gate (`scripts/check-fixture-drift.mjs`) turns every newly-appeared",
    "upstream field into a tracked triage disposition rather than an unnoticed drop —",
    "carried losslessly where a carry channel exists (see `sdk-surface.json` for this",
    "facet's per-field dispositions, including its disclosed `silently-dropped` gaps).",
    "",
    `| \`${peer.name}\` | verified | with | evidence |`,
    "| --- | --- | --- | --- |",
    ...rows,
    END,
  ].join("\n");
}

/** Find the compat block's [start, endExclusive) — each marker must appear
 *  exactly once, in order. Throws otherwise (never a silent mis-splice). */
function findBlock(facet, readme) {
  for (const marker of [BEGIN, END]) {
    const count = readme.split(marker).length - 1;
    if (count !== 1) {
      throw new Error(
        `${facet}/README.md: expected exactly one \`${marker}\` marker, found ${count} — ` +
          `a quoted marker (e.g. in a code fence) must not collide with the real section`,
      );
    }
  }
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (end < begin) {
    throw new Error(`${facet}/README.md: ${END} precedes ${BEGIN}`);
  }
  return { begin, endExclusive: end + END.length };
}

/** Render one facet and report staleness; writes only when !checkOnly. */
async function processFacet(facet, checkOnly) {
  const pkgPath = resolve(typescriptRoot, "packages", facet, "package.json");
  const manifestPath = resolve(typescriptRoot, "packages", facet, "sdk-surface.json");
  const readmePath = resolve(typescriptRoot, "packages", facet, "README.md");

  const [pkg, manifest, readme] = await Promise.all([
    readFile(pkgPath, "utf8").then(JSON.parse),
    readFile(manifestPath, "utf8").then(JSON.parse),
    readFile(readmePath, "utf8"),
  ]);
  if (!Array.isArray(manifest.verified) || manifest.verified.length === 0) {
    throw new Error(`${facet}: sdk-surface.json has no \`verified\` log — seed it first`);
  }

  const { begin, endExclusive } = findBlock(facet, readme);
  const block = renderBlock(pkg, manifest.verified);
  const next = readme.slice(0, begin) + block + readme.slice(endExclusive);
  if (next === readme) return { facet, stale: false };
  if (!checkOnly) await writeFile(readmePath, next, "utf8");
  return { facet, stale: true };
}

/**
 * Gate-callable staleness check (used by check-fixture-drift.mjs): returns
 * finding lines (empty = every README compat table is current). Never writes.
 */
export async function checkCompatStaleness() {
  const findings = [];
  for (const facet of FACETS) {
    try {
      const { stale } = await processFacet(facet, true);
      if (stale) {
        findings.push(
          `  ${facet}: README.md's generated compatibility table is STALE — run \`node scripts/render-compat.mjs\``,
        );
      }
    } catch (err) {
      findings.push(`  ${facet}: render-compat: ${err instanceof Error ? err.message : err}`);
    }
  }
  return findings;
}

async function main() {
  const checkOnly = process.argv.slice(2).includes("--check");
  const results = await Promise.all(FACETS.map((f) => processFacet(f, checkOnly)));
  const stale = results.filter((r) => r.stale);

  if (checkOnly && stale.length > 0) {
    console.error(
      `✖ compatibility table(s) stale in: ${stale.map((r) => r.facet).join(", ")} — run \`node scripts/render-compat.mjs\``,
    );
    process.exit(1);
  }
  for (const r of results) {
    console.log(r.stale ? `✎ ${r.facet}/README.md — compatibility section rewritten` : `✓ ${r.facet}/README.md — up to date`);
  }
}

// Import-safe: only run the CLI when executed directly (the drift gate
// imports checkCompatStaleness from this module).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
